# Generated by Django 5.2.3 on 2025-06-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driving_school', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('pdl_number', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('license_type', models.CharField(max_length=50)),
                ('test_date', models.DateField()),
                ('time_slot', models.CharField(max_length=30)),
                ('document', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
