# Generated by Django 5.2.3 on 2025-06-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
