# Generated by Django 5.2.3 on 2025-06-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
