# Generated by Django 5.2.3 on 2025-07-01 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_role_userprofile_user_type'),
        ('testcentre_mgmt', '0002_testcentre_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testslot',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcentre_mgmt.testcentre'),
        ),
    ]
